name: tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'vitest.config.ts'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/tests.inc.yml
